services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    enviaronment:
      - CHOKIDAR_USEPOLLING=true #garante o hot relond em alguns sistemas
    stdin_open: true
    tty: true  